config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get 'pages/about', to: 'pages#about', as: :about
  get 'pages/newsletter', to: 'pages#newsletter', as: :newsletter
  get 'pages/disclaimer', to: 'pages#disclaimer', as: :disclaimer


  get 'poetries', to: 'poetries#index', as: :poetries
  get "poetries/new", to: "poetries#new"
  post   "poetries", to: "poetries#create"
  get "poetries/:id/edit", to: "poetries#edit", as: :poetries_edit
  patch "poetries/:id", to: "poetries#update"
  get 'poetries/:id', to: 'poetries#show', as: :poetry
  delete "poetries/:id", to: "poetries#destroy"

  get "/amateur_poetries", to: "poetries#amateur_poetries"
  get "/famous_poetries", to: "poetries#famous_poetries"

  # get "poetries/user_poetries", to: "poetries#user_poetries"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poetry.rb
class Poetry < ApplicationRecord
  def self.search(search)
    where("lower(title) LIKE ? OR lower(author) LIKE ? OR lower(country) LIKE ? OR lower(born) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  # def self.amateur(search)
  #   where("poster != ?","Admin")
  # end

  # def self.famous(search)
  #   where("poster = ?","Admin")
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  after_action :verify_authorized, :except => :index, unless: :devise_controller?
  after_action :verify_policy_scoped, :only => :index, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Non sei autorizzato a eseguire questa azione"
    redirect_to(root_path)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include Pundit
    skip_after_action :verify_authorized, only: [:home, :about, :newsletter, :disclaimer]

    skip_before_action :authenticate_user!, only: [:home, :about, :newsletter, :disclaimer]
  # skip_after_action :verify_authorized, except: [:home]
  # after_action :verify_authorized, except: [:home]
  # before_action :authenticate_user!, except: [:home,]

  def home
  end

  def about
  end

  def newsletter
  end

  def disclaimer
  end

end

app/controllers/poetries_controller.rb
class PoetriesController < ApplicationController
  skip_after_action :verify_authorized, only: [:home, :about, :newsletter, :disclaimer, :new, :create, :amateur_poetries, :famous_poetries]
  skip_before_action :authenticate_user!, only: [:home, :about, :newsletter, :disclaimer, :new, :create]

  before_action :set_poetry, only: [:show, :edit, :update, :destroy,]
  before_action :authenticate_user!, except: [:index, :amateur_poetries]

  def index
    if params[:search]
      @poetries = policy_scope(Poetry).search(params[:search]).order("RANDOM()").limit(30)
    else
      @poetries = policy_scope(Poetry).order("RANDOM()").limit(30)
    end
  end

  # def index
  #   if params[:search]
  #     if params[:poetries_type] == "Famous"
  #       @poetries = policy_scope(Poetry).famous.search(params[:search]).order("created_at DESC").limit(30)
  #     elsif params[:poetries_type] == "Amateur"
  #       @poetries = policy_scope(Poetry).amateur.search(params[:search]).order("created_at DESC").limit(30)
  #     else
  #       @poetries = policy_scope(Poetry).search(params[:search]).order("created_at DESC").limit(30)
  #     end
  #   else
  #     @poetries = policy_scope(Poetry).order("RANDOM()").limit(30)
  #   end
  # end

  def amateur_poetries
    @poetries = policy_scope(Poetry).order("RANDOM()").limit(30).where.not(poster: "Admin")
  end

  def famous_poetries
    @poetries = policy_scope(Poetry).order("RANDOM()").limit(30).where(poster: "Admin")
  end


  def show
    authorize @poetry
  end

  def new
    @poetry = Poetry.new
  end

  def create
    Poetry.create(poetry_params)
    redirect_to poetries_path
  end

  def edit
    authorize @poetry
  end

  def update
    authorize @poetry
    @poetry.update(poetry_params)
    redirect_to poetry_path(@poetry)
  end

  def destroy
    authorize @poetry
    @poetry.destroy
    redirect_to poetries_path
  end

  def user_poetries
    @poetries = Poetry.all
  end


  private

  def poetry_params
    params.require(:poetry).permit(:title, :author, :body, :poster, :country)
  end

  def set_poetry
    @poetry = Poetry.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <head>
    <title><%= @title %></title>
  </head>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>

</body>
</html>

app/views/pages/about.html.erb
<% @title="The Poeti: Chi Siamo" %>

<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><b>Chi Siamo</b></h1>
      <br>
    </div>
    <div class="col-sm-5 col-sm-offset-2">
      <%= image_tag "thepoeti_aboutus.jpg", height: 350 %>
      <br>
      <br>
    </div>
    <div class="col-sm-6 col-sm-offset-3">
      <p>
        Cari lettori,
        <br>
        <br>
        Ci presentiamo: Fabio, Jacopo e Francesco, tre ex-bocconiani appassionati di musica, scacchi e ovviamente… poesia. Viviamo a Parigi, appollaiati sulla bella collina di Montmartre che ha ispirato la nascita di ThePoeti. Il progetto é nato durante una delle nostre solite discussioni serali, tra un bicchiere di grappa ed elucubrazioni sul mondo.  Pensiamo che il mondo abbia bisogno di bellezza e sincerità e nulla ci sembra più adatto, in questi tempi veloci e a tratti isterici, del formato poetico per raggiungere questo fine.
        <br>
        <br>
        Ci impegniamo ad aggiungere quotidianamente una o più poesie e migliorare il blog al fine di offrire ai nostri lettori una piacevole sensazione di scoperta ed un respiro dagli stress del quotidiano.
        <br>
        <br>
        The Poeti ha l’ambizione di diventare la più grande pagina di poesia online.  Per questo ci serve l’aiuto di voi avidi lettori ed appassionati per proporci nuove idee, introdurci a nuovi poeti meno conosciuti e suggerire poesie non ancora presenti.</p>
    </div>
      <div class="col-sm-6 col-sm-offset-3">
      <p>
      <a href="mailto:thepoeti@gmail.com">Contattaci</a>
      </p>
    </div>

  </div>
</div>

app/views/pages/disclaimer.html.erb
<% @title="The Poeti: Disclaimer" %>

<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><b>Disclaimer</b></h1>
      <br>
    </div>
    <div class="col-sm-6 col-sm-offset-3">
      <p>
      ThePoeti è un progetto letterario indipendente, nato per sostenere la proliferazione della poesia in ogni sua forma.
      <br>
      <br>

      Tutte le poesie raccolte nel sito sono inserite al solo scopo di promuoverne la diffusione. Qualora ritieni che una delle poesie non sia conforme a rimanere sul sito, invia una segnalazione a <a href="mailto:thepoeti@gmail.com">The Poeti</a> per sollecitarne la rimozione.
      <br>
      </p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% @title="The Poeti" %>

<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), background-image: url('/assets/images/poetry_background_image.jpg');">

  <div class="banner-content">
    <h1>The Poeti</h1>
    <p>Poesie per l'animo</p>
    <a href="poetries" class="btn btn-primary btn-lg"> Esplora le poesie </a>
  </div>
</div>

app/views/pages/newsletter.html.erb
<% @title="The Poeti: Newsletter" %>

<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><b>Newsletter</b></h1>
      <br>
    </div>
    <div class="col-sm-6 col-sm-offset-3">
      <p>
        <i><b>the•poeti</b></i>
        <br>
        <br>
        /po·è·ti/
        <br>
        sostantivo maschile
        <br>
        <br>
        La redazione di thepoeti ti invia una poesia a settimana. Per cominciare la giornata con un po’ di bellezza.
        <br>
        <br>
        Oltre 2000 persone sono già iscritte alla comunità di thepoeti. Non aspettare.
      </p>
    </div>
    <div class="col-sm-6 col-sm-offset-3">
      <br>
      <br>
      <p>Registra la tua email e ricevi una poesia gratis a settimana:</p>
    </div>
  </div>
</div>

app/views/poetries/_form.html.erb
<br>
<div class="container">
  <div class="row ">
    <div class="col-sm-4 col-sm-offset-4">
      <%= form_for(poetry) do |f| %>
      <div class="form-group">
        <%= f.label :title, "Titolo"%>
        <%= f.text_field :title, as: :string, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :body, "Poesia"%>
        <%= f.text_area :body, rows: 20, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :author, "Autore" %>
        <%= f.text_field :author, as: :string, label: false, value: current_user, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :country, "Paese/Nazione" %>
        <%= f.country_select :country, as: :string, class: 'form-control' %>
<!--         <%= f.text_field :country, as: :string, label: false, class: 'form-control' %>
 -->      </div>



      <div class="form-poster-hidden" style="display: none";>
        <div class="form-group">
          <%= f.label :poster, "Chi sta creando la poesia?" %>
          <%= f.text_field :poster, as: :string, label: false, value: current_user, class: 'form-control' %>
        </div>
      </div>

      <%= f.submit "Conferma",  class:"btn btn-secondary btn-lg" %>
      <% end %>
    </div>
  </div>
</div>

app/views/poetries/amateur_poetries.html.erb
<% @title="The Poeti: Poesie scritte da voi" %>


<div class="container">

  <div class="poetries-generator">
    <%= link_to "Genera altre poesie amatoriali" , amateur_poetries_path, :class => "btn btn-primary"%>
  </div>

  <div class="row">
    <% @poetries.each do | poetry| %>
    <div class="col-xs-12 col-sm-4">
      <% if policy(poetry).show? %>
      <%= link_to poetry_path(poetry) do %>
      <div class="card">
        <div class="card-description">
          <h2> <%=poetry.title=%> </h2>
          <% sanitized_body = sanitize(poetry.body.truncate(170), tags: %w(br)) %></p>
          <p> <%= sanitized_body %></p>
          <div class="card-author-and-icon">
            <div class="card-author">
              <p><i><%=poetry.author=%></i></p>
            </div>
            <div class="card-icon">
              <% if poetry.poster=="Admin"  %>
              <p><i class="fas fa-feather"></i></p>
             <% else %>
             <p><i class="fas fa-palette"></i></p>
             <% end %>
           </div>
         </div>
         <div class="card-born-country">
          <div class="card-born">
            <p><%=poetry.born=%>,</p>
          </div>
          <div class="card-country">
            <p> <%= poetry.country=%></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <% end %>
  <!-- </div> -->
</div>
</div>

app/views/poetries/edit.html.erb
<% @title="The Poeti: Modifica una poesia" %>
<%= render 'form', poetry: @poetry %>

app/views/poetries/famous_poetries.html.erb
<% @title="The Poeti: Poesie di aiutori famosi" %>
<div class="container">
  <div class="poetries-generator">
    <%= link_to "Genera altre poesie famose" , famous_poetries_path, :class => "btn btn-primary"%>
  </div>

  <div class="row">
    <% @poetries.each do | poetry| %>
    <div class="col-xs-12 col-sm-4">
      <% if policy(poetry).show? %>
      <%= link_to poetry_path(poetry) do %>
      <div class="card">
        <div class="card-description">
          <h2> <%=poetry.title=%> </h2>
          <% sanitized_body = sanitize(poetry.body.truncate(170), tags: %w(br)) %></p>
          <p> <%= sanitized_body %></p>
          <div class="card-author-and-icon">
            <div class="card-author">
              <p><i><%=poetry.author=%></i></p>
            </div>
            <div class="card-icon">
              <% if poetry.poster=="Admin"  %>
              <p><i class="fas fa-feather"></i></p>
             <% else %>
             <p><i class="fas fa-palette"></i></p>
             <% end %>
           </div>
         </div>
         <div class="card-born-country">
          <div class="card-born">
            <p><%=poetry.born=%>,</p>
          </div>
          <div class="card-country">
            <p> <%= poetry.country=%></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <% end %>
  <!-- </div> -->
</div>
</div>

app/views/poetries/index.html.erb
<% @title="The Poeti: Poesie" %>

<div class="container">
  <div class="poetries-generator">
    <%= link_to "Genera altre poesie" , poetries_path, :class => "btn btn-primary"%>
  </div>

  <div class="row">
    <% @poetries.each do | poetry| %>

    <div class="col-xs-12 col-sm-4">
      <% if policy(poetry).show? %>
      <%= link_to poetry_path(poetry) do %>
      <div class="card">
        <div class="card-description">
          <h2> <%=poetry.title=%> </h2>
          <% sanitized_body = sanitize(poetry.body.truncate(170), tags: %w(br)) %></p>
          <p> <%= sanitized_body %></p>
          <div class="card-author-and-icon">
            <div class="card-author">
              <p><i><%=poetry.author=%></i></p>
            </div>
            <div class="card-icon">
              <% if poetry.poster=="Admin"  %>
              <p><i class="fas fa-feather"></i></p>

             <% else %>
             <p><i class="fas fa-palette"></i></p>
             <% end %>
           </div>
         </div>
         <div class="card-born-country">
          <div class="card-born">
            <p><%=poetry.born=%>,</p>
          </div>
          <div class="card-country">
            <p> <%= poetry.country=%></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <% end %>
  <!-- </div> -->
</div>
</div>

app/views/poetries/new.html.erb
<% @title="The Poeti: Aggiungi una poesia" %>

<%= render 'form', poetry: @poetry %>

app/views/poetries/show.html.erb
<% @title=@poetry.title %>

<br>
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <h2><%= @poetry.title %></h2>
      <p> <%= sanitize(@poetry.body, tags: %w(br)) %> </p>
      <br>
      <br>
      <p><i><%= @poetry.author %><i></p>
      <br>
        <%= link_to "Modifica", poetries_edit_path(@poetry) %>
        <%= link_to "Cancella", poetry_path(@poetry),
        method: :delete,
        data: { confirm: "Sei sicuro di voler cancellare la poesia?" } %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="footer-links">
      <a href="https://www.facebook.com/thepoetiofficial/"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/thepoetiofficial/"><i class="fab fa-facebook"></i></a>
      <a href="https://twitter.com/ThePoetiReal"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
      <%= link_to "Chi Siamo", about_path =%>
      <%= link_to "Newsletter", newsletter_path =%>
      <%= link_to "Disclaimer", disclaimer_path =%>
    </div>
<!--     <div class="footer-copyright">
      <div class="wrapper_inside_footer">
        <div class="footer-wrapper">
          <%= link_to "Chi Siamo", poetries_path =%>
        </div>
      </div>
    </div> -->
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to poetries_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.jpg", height: 50 %>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <%= form_tag(poetries_path, :method => "get", id: "search-form", :class => "search-bar-navbar") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Cerca una poesia" %>
        <%= submit_tag "Cerca" %>
      <% end %>
    <!-- Links when logged in -->


<div class="navbar-wagon-item" id="poesie-dropdown">
      <div class="dropdown">
         <%= link_to "Poesie", poetries_path, class: "navbar-wagon-item navbar-wagon-link", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
            <%= link_to poetries_path do %>
           <%= t(".profile", default: "Tutte") %>
            <% end %>
          <li>
            <%= link_to famous_poetries_path do %>
            <%= t(".profile", default: "D'autore") %>
            <% end %>
          </li>
          <li>
            <%= link_to amateur_poetries_path do %>
            <%= t(".settings", default: "Amatoriali") %>
            <% end %>
          </li>
<!--           <li>
            <%= link_to "#" do %>
            <%= t(".settings", default: "Filtri") %>
            <% end %>
          </li> -->
        </ul>
      </div>
    </div>

<!--
    <%= link_to "Poesie", poetries_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
    <%= link_to "Aggiungi una Poesia", poetries_new_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "user_profile.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_user_registration_path do %>
            <i></i> <%= t(".profile", default: "Modifica Profilo") %>
            <% end %>
          </li>
<!--           <li>
            <%= link_to "#" do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li> -->
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->

<!--         <div id="imaginary_container">
      <div class="input-group stylish-input-group">
        <input type="text" class="form-control"  placeholder="Cerca una poesia" >
        <span class="input-group-addon">
          <button type="submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    </div> -->


    <%= form_tag(poetries_path, :method => "get", id: "search-form", :class => "search-bar-navbar") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Cerca una poesia" %>
    <%= submit_tag "Cerca" %>
    <% end %>

    <%= link_to "Aggiungi una Poesia", poetries_new_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(".sign_in", default: "Login/Registrati"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->

<!-- Mobile logged out
 -->
<% if user_signed_in? %>

  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Modifica profilo", edit_user_registration_path %> </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
</div>

<% else %>

<!-- Mobile logged out
 -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>    <%= link_to t(".sign_in", default: " Login/Registrati"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li> <%= form_tag(poetries_path, :method => "get", id: "search-form", :class => "search-bar-navbar") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Cerca una poesia", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= submit_tag "Cerca", class: "btn btn-primary"%>
      <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<% end %>